### ISSUE TITLE
Android Runtime

### ISSUE THREAD

**Issue by lulasz** [LB--/JSON-Object#1]
I bought the JSON for Android, put the JSON Object into my app. Compiled and got black screen, whole app is not working. No events or something just the JSON Object, looks like the runtime for android isn't working fine, because on Windows is working normal.

It stuck on black screen and sometimes crash.
Any fixes?

**Comment by LB--** [comment]
Yes, I fixed that issue years ago but I am unable to update the version that is in the clickstore. Email me or [PM me on the forums](https://community.clickteam.com/private.php?do=newpm&u=6786) and I can send you the updated version.

**Comment by lulasz** [comment]
Good to know! I have send you a PM on the forum. :)

**Comment by dsissongh** [comment]
I ran into this after tons of searching and am relieved that this could resolve the problem I have.  I have sent a PM as well.

**Comment by Corborus** [comment]
Hello! We can´t send you PMs so I don´t know how to contact you! I have the same problem of the black screen! I really need the new version of the object! can you please send it to me? thanks

**Comment by lulasz** [comment]
E-mail me, I got a fix.

**Comment by Corborus** [comment]
> 
> 
> E-mail me, I got a fix.

Done! Thank you
