### ISSUE TITLE
Problem with Cyrillic symbols on HTML5

### ISSUE THREAD

**Issue by GKProduction** [LB--/JSON-Object#4]
It seems that the extension has problems with the selected encoding on the HTML5 runtime.

Here is how the Cyrillic symbols are displayed on Windows-build:
![Снимок экрана 2024-05-26 185016](https://github.com/LB--/JSON-Object/assets/75405357/a0920a91-dab3-4385-a135-18cb009d5ffd)

And now, as on a HTML5-build:
![Снимок экрана 2024-05-26 184928](https://github.com/LB--/JSON-Object/assets/75405357/38fcd819-3a63-4420-a97f-ed039c1b5e7d)

The file from which the text is taken is saved with an encoding in UTF-8.

It's possible to solve this problem? Or is it possible to fix this?

**Comment by GKProduction** [comment]
![image](https://github.com/LB--/JSON-Object/assets/75405357/9f473ad7-6367-41eb-a7f3-6de71e2cf9a1)
Well this is not JSON issue. It's Edit Box problem, but I will not delete the post if this information will be useful for someone.

**Comment by LB--** [comment]
You might need to edit your application properties in Fusion to tell it to use UTF-8 without a byte-order mark:
![image](https://github.com/LB--/JSON-Object/assets/1296838/95891304-271c-4e2b-9ed6-8bf2159523b4)

**Comment by GKProduction** [comment]
> You might need to edit your application properties in Fusion to tell it to use UTF-8 without a byte-order mark

Oooh trust me I actually tried this but it didn't help with HTML5 runtime.
